language: java
script: mvn clean integration-test
notifications:
  slack:
    rooms:
      secure: QNELjlO305K6wBseMZwRjB2cYS+p0ZWjJUk0EvDrvM95ZmBBbw2vBXp59rgEc//LTQxx0O/sRdrPzshksdZwnDWumStRgxYT5pcmbwpiS9sO3Y5FREU34jy2nXFBNQHP2AK6J2jy5ULxYIJ/Dau0tbiMygABDwln0kisBZIqv7+SCBl142UKTx3cGYa35XoJ4UPxseO18cGB5hH13TAN7pH1Slu8pprs8sKX4MFu/4/IlYGkF5ZaTAcCbWsYAJpFWGwK9DMRXFjrSwvpGBA2s8PqXQsPQI+gnJm7bCujw0kKgpZqVw9Onw+9C4pin2NztlG0KGLlZ3mLjtNPkQ/slYWDDfiAG9P8xz3ylKbiyrtJbzmtAQoXB0kPVuVhiZ6zBGrUnw9hvzkDEmq6cJRvXNie8JevTs81kzYrAcI0lwOibcWtmTlkvTKax8BTzjBaHsTRURotVq2uBpGwi8+Y90FiahRpl4NPFJhJiy7wpwrzJHDbVgnrq8gpK8XfNtZD6KRD4XzXf65t8FiwjSaJXnZwQQ4oFhTYKf699Wdk3Z4oA1PvvMCsoQfp2ex9WQzyOvOBtykXad2gI5fKF98O2WRvLJb/DURJyqhJQ1eh3wjKttTcGQouL8t3XKjt8ozZ3FxfcHRN2OEpjhhCoj6qB3tALs/aCdYkLwzDW7i44CM=
    on_success: change
