language: java
script: mvn verify
cache:
  directories:
  - "$HOME/.m2"
notifications:
  slack:
    rooms:
      secure: e661qGWYxDLdaOvdjqzfRPBQzN2CBOpKos7miIR8VePQjMBH0WFypHb8x9Gb4Tb/K2XChxuwayOxVLhZPonmRxaEszCp5q3NCFMtiv6FWyNMjbMzhVos2eyAMIoghLRBgzeQnjks2oGilWhAP+jt2BejStB9ulZ7csx4qQU/YwCOERz+PagWNjDDe0QP1ylx9qHffZqG8yzTwaliIZehRN4hJzAnlr3A+Fb5djAGp3Ptlagjwjd1W2x+BESo83J0WciMprzMF4lCs0tjFAHl6wHa0iM8UVI4+ZuygjiptpXwe/Q9Z5v0H6wzYbUUh2J9jOrQdSLm+/rKlisYmpQlPoU3/1FRpWKd4BtJNbZg1ux7ssEXEMxQClEmjGcE1K87HMbkqqKw4kcXiJmVBGWuUyte0HkzXqkkhwhM2vvRpa5fnq4lUMqsnZBzbhsfkqTAp00dGMArEVZm8roHCLP2rXkFKZcqVtXXKlF15Y8Yr3YbUJb/WlT5AzJDL19j4smFr5M9mCv+3Z/qncSc4A9tQCw3GNtf8jhEEZpad5ZNgO7UxyI80TOam7l9vBQrMkiHAWkuP8YtJnVXNQjzjv23DLwjLpHdlmFoREG2tXq4LmYw+CvPR6lUi1e9qvvui4MK9zMiYxH3DBQkVog2i1mPI4e1dki6A9ZAN/VMG7FRY5k=
    on_success: change
    on_failure: change
